"""update timezone

Revision ID: 1e25b4c0b33f
Revises: convert_chat_ids_to_uuid
Create Date: 2026-03-22 13:17:20.040566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '1e25b4c0b33f'
down_revision: Union[str, Sequence[str], None] = 'convert_chat_ids_to_uuid'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auctions', 'start_time',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('auctions', 'buyer',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               type_=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('bids', 'bid_time',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bids', 'bid_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('auctions', 'buyer',
               existing_type=sa.VARCHAR(length=64),
               type_=mssql.UNIQUEIDENTIFIER(),
               existing_nullable=True)
    op.alter_column('auctions', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
