"""add_order_sync_columns

Revision ID: 60c90d150bcf
Revises: 0d4241af2805
Create Date: 2026-06-02 09:41:56.593242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '60c90d150bcf'
down_revision: Union[str, Sequence[str], None] = '0d4241af2805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            """
            SELECT 1
            FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_NAME = :table_name
            """
        ),
        {"table_name": table_name},
    ).first()
    return result is not None


def _index_exists(table_name: str, index_name: str) -> bool:
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            """
            SELECT 1
            FROM sys.indexes
            WHERE object_id = OBJECT_ID(:table_name)
              AND name = :index_name
            """
        ),
        {"table_name": table_name, "index_name": index_name},
    ).first()
    return result is not None


def _column_exists(table_name: str, column_name: str) -> bool:
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            """
            SELECT 1
            FROM sys.columns
            WHERE object_id = OBJECT_ID(:table_name)
              AND name = :column_name
            """
        ),
        {"table_name": table_name, "column_name": column_name},
    ).first()
    return result is not None


def _fk_exists(table_name: str, fk_name: str) -> bool:
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            """
            SELECT 1
            FROM sys.foreign_keys
            WHERE name = :fk_name
              AND parent_object_id = OBJECT_ID(:table_name)
            """
        ),
        {"table_name": table_name, "fk_name": fk_name},
    ).first()
    return result is not None


def _fk_exists_between(from_table: str, to_table: str) -> bool:
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            """
            SELECT 1
            FROM sys.foreign_keys
            WHERE parent_object_id = OBJECT_ID(:from_table)
              AND referenced_object_id = OBJECT_ID(:to_table)
            """
        ),
        {"from_table": from_table, "to_table": to_table},
    ).first()
    return result is not None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if _table_exists('admins'):
        op.drop_table('admins')
    if _index_exists('analytics_sales_snapshots', 'IX_analytics_sales_snapshots_snapshot_at'):
        op.drop_index(op.f('IX_analytics_sales_snapshots_snapshot_at'), table_name='analytics_sales_snapshots')
    if _table_exists('analytics_sales_snapshots'):
        op.drop_table('analytics_sales_snapshots')
    if _index_exists('analytics_overview_snapshots', 'IX_analytics_overview_snapshots_snapshot_at'):
        op.drop_index(op.f('IX_analytics_overview_snapshots_snapshot_at'), table_name='analytics_overview_snapshots')
    if _table_exists('analytics_overview_snapshots'):
        op.drop_table('analytics_overview_snapshots')
    if _index_exists('analytics_buyers_snapshots', 'IX_analytics_buyers_snapshots_snapshot_at'):
        op.drop_index(op.f('IX_analytics_buyers_snapshots_snapshot_at'), table_name='analytics_buyers_snapshots')
    if _table_exists('analytics_buyers_snapshots'):
        op.drop_table('analytics_buyers_snapshots')
    if _index_exists('analytics_blends_snapshots', 'IX_analytics_blends_snapshots_snapshot_at'):
        op.drop_index(op.f('IX_analytics_blends_snapshots_snapshot_at'), table_name='analytics_blends_snapshots')
    if _table_exists('analytics_blends_snapshots'):
        op.drop_table('analytics_blends_snapshots')
    if _index_exists('analytics_purchases_snapshots', 'IX_analytics_purchases_snapshots_snapshot_at'):
        op.drop_index(op.f('IX_analytics_purchases_snapshots_snapshot_at'), table_name='analytics_purchases_snapshots')
    if _table_exists('analytics_purchases_snapshots'):
        op.drop_table('analytics_purchases_snapshots')
    if _index_exists('Messages', 'IX_Messages_Timestamp'):
        op.drop_index(op.f('IX_Messages_Timestamp'), table_name='Messages')
    if not _index_exists('Messages', 'ix_Messages_Timestamp') and not _index_exists('Messages', 'IX_Messages_Timestamp'):
        op.create_index(op.f('ix_Messages_Timestamp'), 'Messages', ['Timestamp'], unique=False)
    if _fk_exists('Messages', 'FK_Messages_Conversations'):
        op.drop_constraint(op.f('FK_Messages_Conversations'), 'Messages', type_='foreignkey')
    if not _fk_exists_between('Messages', 'Conversations'):
        op.create_foreign_key(None, 'Messages', 'Conversations', ['ConversationID'], ['ConversationID'], ondelete='CASCADE')
    op.alter_column('auctions', 'auction_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('auctions', 'company_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('auctions', 'estate_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    if not _index_exists('auctions', 'ix_auctions_auction_id') and not _index_exists('auctions', 'IX_auctions_auction_id'):
        op.create_index(op.f('ix_auctions_auction_id'), 'auctions', ['auction_id'], unique=False)
    if not _index_exists('auctions', 'ix_auctions_custom_auction_id') and not _index_exists('auctions', 'IX_auctions_custom_auction_id'):
        op.create_index(op.f('ix_auctions_custom_auction_id'), 'auctions', ['custom_auction_id'], unique=True)
    if not _index_exists('bids', 'ix_bids_auction_id') and not _index_exists('bids', 'IX_bids_auction_id'):
        op.create_index(op.f('ix_bids_auction_id'), 'bids', ['auction_id'], unique=False)
    if not _index_exists('bids', 'ix_bids_bid_id') and not _index_exists('bids', 'IX_bids_bid_id'):
        op.create_index(op.f('ix_bids_bid_id'), 'bids', ['bid_id'], unique=False)
    if not _index_exists('bids', 'ix_bids_buyer_id') and not _index_exists('bids', 'IX_bids_buyer_id'):
        op.create_index(op.f('ix_bids_buyer_id'), 'bids', ['buyer_id'], unique=False)
    if _fk_exists('bids', 'FK_bids_auctions'):
        op.drop_constraint(op.f('FK_bids_auctions'), 'bids', type_='foreignkey')
    if not _fk_exists_between('bids', 'auctions'):
        op.create_foreign_key(None, 'bids', 'auctions', ['auction_id'], ['auction_id'], ondelete='CASCADE')
    if not _index_exists('financial_details', 'ix_financial_details_id') and not _index_exists('financial_details', 'IX_financial_details_id'):
        op.create_index(op.f('ix_financial_details_id'), 'financial_details', ['id'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Enum('order', 'system', 'promo', 'alert', name='notificationtypeenum'),
               existing_nullable=False,
               existing_server_default=sa.text("('system')"))
    if _index_exists('notifications', 'IX_notifications_user_id'):
        op.drop_index(op.f('IX_notifications_user_id'), table_name='notifications')
    if not _column_exists('orders', 'display_order_id'):
        op.add_column('orders', sa.Column('display_order_id', sa.String(length=50), nullable=True))
    if not _column_exists('orders', 'seller_id'):
        op.add_column('orders', sa.Column('seller_id', mssql.UNIQUEIDENTIFIER(), nullable=True))
    if not _column_exists('orders', 'payment_status'):
        op.add_column('orders', sa.Column('payment_status', sa.String(length=50), nullable=False, server_default='pending'))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=9, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False)
    if not _index_exists('orders', 'ix_orders_display_order_id') and not _index_exists('orders', 'IX_orders_display_order_id'):
        op.create_index(op.f('ix_orders_display_order_id'), 'orders', ['display_order_id'], unique=True)
    if not _index_exists('orders', 'ix_orders_order_id') and not _index_exists('orders', 'IX_orders_order_id'):
        op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    if not _fk_exists_between('orders', 'users'):
        op.create_foreign_key(None, 'orders', 'users', ['seller_id'], ['user_id'])
    if not _index_exists('payment_details', 'ix_payment_details_payment_id') and not _index_exists('payment_details', 'IX_payment_details_payment_id'):
        op.create_index(op.f('ix_payment_details_payment_id'), 'payment_details', ['payment_id'], unique=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('users', 'shipping_address',
               existing_type=sa.VARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('users', 'verification_status',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
    if not _index_exists('users', 'ix_users_email') and not _index_exists('users', 'IX_users_email'):
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    if not _index_exists('users', 'ix_users_user_id') and not _index_exists('users', 'IX_users_user_id'):
        op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    
    # Recreate empty violations table to change types cleanly on SQL Server
    if _table_exists('violations'):
        op.drop_table('violations')
    
    op.create_table(
        'violations',
        sa.Column('violation_id', mssql.UNIQUEIDENTIFIER(), nullable=False, server_default=sa.text('NEWID()')),
        sa.Column('sender_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column('violator_id', sa.String(length=255), nullable=False),
        sa.Column('auction_id', sa.String(length=255), nullable=True),
        sa.Column('violation_type', sa.Enum('fraud', 'scam', 'harassment', 'fake_product', 'payment_issue', 'other', name='violationtypeenum'), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('status', sa.Enum('open', 'under_review', 'resolved', 'closed', name='violationstatusenum'), nullable=False, server_default=sa.text("('open')")),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('GETUTCDATE()')),
        sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name='fk_violations_sender_id'),
        sa.PrimaryKeyConstraint('violation_id')
    )
    
    if not _index_exists('watch_lists', 'ix_watch_lists_id') and not _index_exists('watch_lists', 'IX_watch_lists_id'):
        op.create_index(op.f('ix_watch_lists_id'), 'watch_lists', ['id'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watch_lists_id'), table_name='watch_lists')
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.alter_column('violations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('violations', 'status',
               existing_type=sa.Enum('open', 'under_review', 'resolved', 'closed', name='violationstatusenum'),
               type_=sa.VARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               existing_server_default=sa.text("('open')"))
    op.alter_column('violations', 'violation_type',
               existing_type=sa.Enum('fraud', 'scam', 'harassment', 'fake_product', 'payment_issue', 'other', name='violationtypeenum'),
               type_=sa.VARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('violations', 'sender_id',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('violations', 'violation_id',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'verification_status',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('users', 'shipping_address',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_index(op.f('ix_payment_details_payment_id'), table_name='payment_details')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_display_order_id'), table_name='orders')
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=9, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'seller_id')
    op.drop_column('orders', 'display_order_id')
    op.create_index(op.f('IX_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('order', 'system', 'promo', 'alert', name='notificationtypeenum'),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               existing_server_default=sa.text("('system')"))
    op.drop_index(op.f('ix_financial_details_id'), table_name='financial_details')
    op.drop_constraint(None, 'bids', type_='foreignkey')
    op.create_foreign_key(op.f('FK_bids_auctions'), 'bids', 'auctions', ['auction_id'], ['auction_id'])
    op.drop_index(op.f('ix_bids_buyer_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_bid_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_auction_id'), table_name='bids')
    op.drop_index(op.f('ix_auctions_custom_auction_id'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_auction_id'), table_name='auctions')
    op.alter_column('auctions', 'estate_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('auctions', 'company_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('auctions', 'auction_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.drop_constraint(None, 'Messages', type_='foreignkey')
    op.create_foreign_key(op.f('FK_Messages_Conversations'), 'Messages', 'Conversations', ['ConversationID'], ['ConversationID'])
    op.drop_index(op.f('ix_Messages_Timestamp'), table_name='Messages')
    op.create_index(op.f('IX_Messages_Timestamp'), 'Messages', ['Timestamp'], unique=False)
    op.create_table('analytics_purchases_snapshots',
    sa.Column('snapshot_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.Column('summary_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('purchase_volume_by_grade_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('price_trends_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('price_trend_grades_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('source_distribution_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('supplier_contribution_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('PK__analytic__C27CFBF794FB9AEC'))
    )
    op.create_index(op.f('IX_analytics_purchases_snapshots_snapshot_at'), 'analytics_purchases_snapshots', ['snapshot_at'], unique=False)
    op.create_table('analytics_blends_snapshots',
    sa.Column('snapshot_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.Column('payload_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('PK__analytic__C27CFBF73B07CF5D'))
    )
    op.create_index(op.f('IX_analytics_blends_snapshots_snapshot_at'), 'analytics_blends_snapshots', ['snapshot_at'], unique=False)
    op.create_table('analytics_buyers_snapshots',
    sa.Column('snapshot_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.Column('payload_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('PK__analytic__C27CFBF745125AEF'))
    )
    op.create_index(op.f('IX_analytics_buyers_snapshots_snapshot_at'), 'analytics_buyers_snapshots', ['snapshot_at'], unique=False)
    op.create_table('analytics_overview_snapshots',
    sa.Column('snapshot_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.Column('kpis_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('revenue_by_month_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('tea_grade_distribution_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('top_blends_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('quick_stats_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('PK__analytic__C27CFBF707191A4E'))
    )
    op.create_index(op.f('IX_analytics_overview_snapshots_snapshot_at'), 'analytics_overview_snapshots', ['snapshot_at'], unique=False)
    op.create_table('analytics_sales_snapshots',
    sa.Column('snapshot_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.Column('summary_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('auction_performance_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('grade_wise_prices_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('selling_trends_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('seller_performance_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('bid_volume_analysis_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('PK__analytic__C27CFBF7330E40FE'))
    )
    op.create_index(op.f('IX_analytics_sales_snapshots_snapshot_at'), 'analytics_sales_snapshots', ['snapshot_at'], unique=False)
    op.create_table('admins',
    sa.Column('admin_id', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text("('Admin')"), autoincrement=False, nullable=True),
    sa.Column('joined_date', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('last_login', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text("('ACTIVE')"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('admin_id', name=op.f('PK__admins__43AA4141DECA5234'))
    )
    # ### end Alembic commands ###
