"""add_order_sync_columns

Revision ID: 60c90d150bcf
Revises: 0d4241af2805
Create Date: 2026-06-02 09:41:56.593242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '60c90d150bcf'
down_revision: Union[str, Sequence[str], None] = '0d4241af2805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    op.drop_index(op.f('IX_analytics_sales_snapshots_snapshot_at'), table_name='analytics_sales_snapshots')
    op.drop_table('analytics_sales_snapshots')
    op.drop_index(op.f('IX_analytics_overview_snapshots_snapshot_at'), table_name='analytics_overview_snapshots')
    op.drop_table('analytics_overview_snapshots')
    op.drop_index(op.f('IX_analytics_buyers_snapshots_snapshot_at'), table_name='analytics_buyers_snapshots')
    op.drop_table('analytics_buyers_snapshots')
    op.drop_index(op.f('IX_analytics_blends_snapshots_snapshot_at'), table_name='analytics_blends_snapshots')
    op.drop_table('analytics_blends_snapshots')
    op.drop_index(op.f('IX_analytics_purchases_snapshots_snapshot_at'), table_name='analytics_purchases_snapshots')
    op.drop_table('analytics_purchases_snapshots')
    op.drop_index(op.f('IX_Messages_Timestamp'), table_name='Messages')
    op.create_index(op.f('ix_Messages_Timestamp'), 'Messages', ['Timestamp'], unique=False)
    op.drop_constraint(op.f('FK_Messages_Conversations'), 'Messages', type_='foreignkey')
    op.create_foreign_key(None, 'Messages', 'Conversations', ['ConversationID'], ['ConversationID'], ondelete='CASCADE')
    op.alter_column('auctions', 'auction_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('auctions', 'company_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('auctions', 'estate_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.create_index(op.f('ix_auctions_auction_id'), 'auctions', ['auction_id'], unique=False)
    op.create_index(op.f('ix_auctions_custom_auction_id'), 'auctions', ['custom_auction_id'], unique=True)
    op.create_index(op.f('ix_bids_auction_id'), 'bids', ['auction_id'], unique=False)
    op.create_index(op.f('ix_bids_bid_id'), 'bids', ['bid_id'], unique=False)
    op.create_index(op.f('ix_bids_buyer_id'), 'bids', ['buyer_id'], unique=False)
    op.drop_constraint(op.f('FK_bids_auctions'), 'bids', type_='foreignkey')
    op.create_foreign_key(None, 'bids', 'auctions', ['auction_id'], ['auction_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_financial_details_id'), 'financial_details', ['id'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Enum('order', 'system', 'promo', 'alert', name='notificationtypeenum'),
               existing_nullable=False,
               existing_server_default=sa.text("('system')"))
    op.drop_index(op.f('IX_notifications_user_id'), table_name='notifications')
    op.add_column('orders', sa.Column('display_order_id', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('seller_id', mssql.UNIQUEIDENTIFIER(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(length=50), nullable=False))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=9, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_orders_display_order_id'), 'orders', ['display_order_id'], unique=True)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['seller_id'], ['user_id'])
    op.create_index(op.f('ix_payment_details_payment_id'), 'payment_details', ['payment_id'], unique=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('users', 'shipping_address',
               existing_type=sa.VARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('users', 'verification_status',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.alter_column('violations', 'violation_id',
               existing_type=sa.INTEGER(),
               type_=mssql.UNIQUEIDENTIFIER(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.alter_column('violations', 'sender_id',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=mssql.UNIQUEIDENTIFIER(),
               nullable=False)
    op.alter_column('violations', 'violation_type',
               existing_type=sa.VARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Enum('fraud', 'scam', 'harassment', 'fake_product', 'payment_issue', 'other', name='violationtypeenum'),
               existing_nullable=False)
    op.alter_column('violations', 'status',
               existing_type=sa.VARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Enum('open', 'under_review', 'resolved', 'closed', name='violationstatusenum'),
               existing_nullable=False,
               existing_server_default=sa.text("('open')"))
    op.alter_column('violations', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.create_foreign_key(None, 'violations', 'users', ['sender_id'], ['user_id'])
    op.create_index(op.f('ix_watch_lists_id'), 'watch_lists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watch_lists_id'), table_name='watch_lists')
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.alter_column('violations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('violations', 'status',
               existing_type=sa.Enum('open', 'under_review', 'resolved', 'closed', name='violationstatusenum'),
               type_=sa.VARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               existing_server_default=sa.text("('open')"))
    op.alter_column('violations', 'violation_type',
               existing_type=sa.Enum('fraud', 'scam', 'harassment', 'fake_product', 'payment_issue', 'other', name='violationtypeenum'),
               type_=sa.VARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('violations', 'sender_id',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('violations', 'violation_id',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'verification_status',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('users', 'shipping_address',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_index(op.f('ix_payment_details_payment_id'), table_name='payment_details')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_display_order_id'), table_name='orders')
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=9, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'seller_id')
    op.drop_column('orders', 'display_order_id')
    op.create_index(op.f('IX_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('order', 'system', 'promo', 'alert', name='notificationtypeenum'),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               existing_server_default=sa.text("('system')"))
    op.drop_index(op.f('ix_financial_details_id'), table_name='financial_details')
    op.drop_constraint(None, 'bids', type_='foreignkey')
    op.create_foreign_key(op.f('FK_bids_auctions'), 'bids', 'auctions', ['auction_id'], ['auction_id'])
    op.drop_index(op.f('ix_bids_buyer_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_bid_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_auction_id'), table_name='bids')
    op.drop_index(op.f('ix_auctions_custom_auction_id'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_auction_id'), table_name='auctions')
    op.alter_column('auctions', 'estate_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('auctions', 'company_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('auctions', 'auction_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.drop_constraint(None, 'Messages', type_='foreignkey')
    op.create_foreign_key(op.f('FK_Messages_Conversations'), 'Messages', 'Conversations', ['ConversationID'], ['ConversationID'])
    op.drop_index(op.f('ix_Messages_Timestamp'), table_name='Messages')
    op.create_index(op.f('IX_Messages_Timestamp'), 'Messages', ['Timestamp'], unique=False)
    op.create_table('analytics_purchases_snapshots',
    sa.Column('snapshot_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.Column('summary_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('purchase_volume_by_grade_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('price_trends_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('price_trend_grades_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('source_distribution_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('supplier_contribution_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('PK__analytic__C27CFBF794FB9AEC'))
    )
    op.create_index(op.f('IX_analytics_purchases_snapshots_snapshot_at'), 'analytics_purchases_snapshots', ['snapshot_at'], unique=False)
    op.create_table('analytics_blends_snapshots',
    sa.Column('snapshot_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.Column('payload_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('PK__analytic__C27CFBF73B07CF5D'))
    )
    op.create_index(op.f('IX_analytics_blends_snapshots_snapshot_at'), 'analytics_blends_snapshots', ['snapshot_at'], unique=False)
    op.create_table('analytics_buyers_snapshots',
    sa.Column('snapshot_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.Column('payload_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('PK__analytic__C27CFBF745125AEF'))
    )
    op.create_index(op.f('IX_analytics_buyers_snapshots_snapshot_at'), 'analytics_buyers_snapshots', ['snapshot_at'], unique=False)
    op.create_table('analytics_overview_snapshots',
    sa.Column('snapshot_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.Column('kpis_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('revenue_by_month_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('tea_grade_distribution_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('top_blends_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('quick_stats_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('PK__analytic__C27CFBF707191A4E'))
    )
    op.create_index(op.f('IX_analytics_overview_snapshots_snapshot_at'), 'analytics_overview_snapshots', ['snapshot_at'], unique=False)
    op.create_table('analytics_sales_snapshots',
    sa.Column('snapshot_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.Column('summary_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('auction_performance_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('grade_wise_prices_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('selling_trends_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('seller_performance_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('bid_volume_analysis_json', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('PK__analytic__C27CFBF7330E40FE'))
    )
    op.create_index(op.f('IX_analytics_sales_snapshots_snapshot_at'), 'analytics_sales_snapshots', ['snapshot_at'], unique=False)
    op.create_table('admins',
    sa.Column('admin_id', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text("('Admin')"), autoincrement=False, nullable=True),
    sa.Column('joined_date', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('last_login', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text("('ACTIVE')"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('admin_id', name=op.f('PK__admins__43AA4141DECA5234'))
    )
    # ### end Alembic commands ###
