"""add admin, violation, verification_status

Revision ID: d168e52fdc48
Revises: b4a9a7d1c2e3
Create Date: 2026-04-21 12:53:14.637902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'd168e52fdc48'
down_revision: Union[str, Sequence[str], None] = 'b4a9a7d1c2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_names(table_name: str) -> set[str]:
    bind = op.get_bind()
    inspector = inspect(bind)
    return {column["name"] for column in inspector.get_columns(table_name)}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BlendComposition')
    op.drop_table('TeaPurchase')
    op.drop_table('BlendPurchaseMapping')
    op.drop_table('TeaBlendSale')
    op.drop_table('Customer')
    op.alter_column('Conversations', 'IsPinned',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
    op.drop_index(op.f('IX_Messages_ConversationID'), table_name='Messages')
    op.create_index(op.f('ix_Messages_ConversationID'), 'Messages', ['ConversationID'], unique=False)
    op.create_index(op.f('ix_Messages_MessageID'), 'Messages', ['MessageID'], unique=False)
    op.alter_column('auctions', 'start_time',
               existing_type=mssql.DATETIMEOFFSET(),
               nullable=False)
    op.alter_column('auctions', 'buyer',
               existing_type=sa.VARCHAR(length=64, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=mssql.UNIQUEIDENTIFIER(),
               existing_nullable=True)
    if 'verification_status' not in _column_names('users'):
        op.add_column('users', sa.Column('verification_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if 'verification_status' in _column_names('users'):
        op.drop_column('users', 'verification_status')
    op.alter_column('auctions', 'buyer',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               type_=sa.VARCHAR(length=64, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('auctions', 'start_time',
               existing_type=mssql.DATETIMEOFFSET(),
               nullable=True)
    op.drop_index(op.f('ix_Messages_MessageID'), table_name='Messages')
    op.drop_index(op.f('ix_Messages_ConversationID'), table_name='Messages')
    op.create_index(op.f('IX_Messages_ConversationID'), 'Messages', ['ConversationID'], unique=False)
    op.alter_column('Conversations', 'IsPinned',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
    op.create_table('Customer',
    sa.Column('CustomerID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Region', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('CustomerID', name=op.f('PK__Customer__A4AE64B88FFE0BB5'))
    )
    op.create_table('TeaBlendSale',
    sa.Column('SaleID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('CustomerID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BlendName', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PricePerKg', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('QuantityKg', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('SaleDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customer.CustomerID'], name=op.f('FK_TeaBlendSale_Customer')),
    sa.PrimaryKeyConstraint('SaleID', name=op.f('PK__TeaBlend__1EE3C41FFECCEB82'))
    )
    op.create_table('BlendPurchaseMapping',
    sa.Column('MappingID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('SaleID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PurchaseID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Standard', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('QuantityUsedKg', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['PurchaseID'], ['TeaPurchase.PurchaseID'], name=op.f('FK_Mapping_Purchase')),
    sa.ForeignKeyConstraint(['SaleID'], ['TeaBlendSale.SaleID'], name=op.f('FK_Mapping_Sale')),
    sa.PrimaryKeyConstraint('MappingID', name=op.f('PK__BlendPur__8B5781BD6ECE6AC9'))
    )
    op.create_table('TeaPurchase',
    sa.Column('PurchaseID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('SourceType', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Standard', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PricePerKg', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('QuantityKg', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('PurchaseDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('PurchaseID', name=op.f('PK__TeaPurch__6B0A6BDE2D04984F'))
    )
    op.create_table('BlendComposition',
    sa.Column('CompositionID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('BlendID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Standard', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Ratio', sa.DECIMAL(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('CompositionID', name=op.f('PK_BlendComposition'))
    )
    # ### end Alembic commands ###
