"""update tables

Revision ID: d62fe694cc91
Revises: 01041068504a
Create Date: 2026-03-10 23:36:53.475164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'd62fe694cc91'
down_revision: Union[str, Sequence[str], None] = '01041068504a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BlendComposition_BlendID'), table_name='BlendComposition')
    op.drop_table('BlendComposition')
    op.drop_index(op.f('ix_BlendPurchaseMapping_MappingID'), table_name='BlendPurchaseMapping')
    op.drop_table('BlendPurchaseMapping')
    op.drop_index(op.f('ix_TeaBlendSale_SaleID'), table_name='TeaBlendSale')
    op.drop_table('TeaBlendSale')
    op.drop_index(op.f('ix_TeaPurchase_PurchaseID'), table_name='TeaPurchase')
    op.drop_table('TeaPurchase')
    op.drop_index(op.f('ix_Customer_CustomerID'), table_name='Customer')
    op.drop_table('Customer')
    op.alter_column('Conversations', 'Title',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('Conversations', 'CreatedAt',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('Conversations', 'UpdatedAt',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('Conversations', 'MessageCount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Conversations', 'IsActive',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text("('1')"))
    # Check if index exists before dropping using raw SQL
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT name FROM sys.indexes WHERE object_id = OBJECT_ID('Conversations') AND name = 'ix_Conversations_ConversationID'"))
    if result.fetchone():
        op.drop_index(op.f('ix_Conversations_ConversationID'), table_name='Conversations')
    
    result = conn.execute(sa.text("SELECT name FROM sys.indexes WHERE object_id = OBJECT_ID('Conversations') AND name = 'ix_Conversations_IsActive'"))
    if result.fetchone():
        op.drop_index(op.f('ix_Conversations_IsActive'), table_name='Conversations')
    
    result = conn.execute(sa.text("SELECT name FROM sys.indexes WHERE object_id = OBJECT_ID('Conversations') AND name = 'ix_Conversations_UserID'"))
    if result.fetchone():
        op.drop_index(op.f('ix_Conversations_UserID'), table_name='Conversations')
    op.alter_column('auctions', 'auction_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('auctions', 'company_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('auctions', 'estate_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=256),
               existing_nullable=False)
    # Check if column exists before dropping
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'users' AND COLUMN_NAME = 'is_active'"))
    if result.fetchone():
        op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', mssql.BIT(), autoincrement=False, nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('auctions', 'estate_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('auctions', 'company_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('auctions', 'auction_name',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.create_index(op.f('ix_Conversations_UserID'), 'Conversations', ['UserID'], unique=False)
    op.create_index(op.f('ix_Conversations_IsActive'), 'Conversations', ['IsActive'], unique=False)
    op.create_index(op.f('ix_Conversations_ConversationID'), 'Conversations', ['ConversationID'], unique=False)
    op.alter_column('Conversations', 'IsActive',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text("('1')"))
    op.alter_column('Conversations', 'MessageCount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Conversations', 'UpdatedAt',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('Conversations', 'CreatedAt',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('Conversations', 'Title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.create_table('Customer',
    sa.Column('CustomerID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Region', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('CustomerID', name=op.f('PK__Customer__A4AE64B8E09B0A9C'))
    )
    op.create_index(op.f('ix_Customer_CustomerID'), 'Customer', ['CustomerID'], unique=False)
    op.create_table('TeaPurchase',
    sa.Column('PurchaseID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('SourceType', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Standard', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PricePerKg', sa.DECIMAL(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('QuantityKg', sa.DECIMAL(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('PurchaseDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('PurchaseID', name=op.f('PK__TeaPurch__6B0A6BDE9BE661E9'))
    )
    op.create_index(op.f('ix_TeaPurchase_PurchaseID'), 'TeaPurchase', ['PurchaseID'], unique=False)
    op.create_table('TeaBlendSale',
    sa.Column('SaleID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('CustomerID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BlendName', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PricePerKg', sa.DECIMAL(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('QuantityKg', sa.DECIMAL(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('SaleDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('SaleID', name=op.f('PK__TeaBlend__1EE3C41F5A02C313'))
    )
    op.create_index(op.f('ix_TeaBlendSale_SaleID'), 'TeaBlendSale', ['SaleID'], unique=False)
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B61BB008626'))
    )
    op.create_table('BlendPurchaseMapping',
    sa.Column('MappingID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('SaleID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PurchaseID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Standard', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('QuantityUsedKg', sa.DECIMAL(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('MappingID', name=op.f('PK__BlendPur__8B5781BD9B76BA96'))
    )
    op.create_index(op.f('ix_BlendPurchaseMapping_MappingID'), 'BlendPurchaseMapping', ['MappingID'], unique=False)
    op.create_table('BlendComposition',
    sa.Column('BlendID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Standard', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Ratio', sa.DECIMAL(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('BlendID', name=op.f('PK__BlendCom__69BE04978C47B4C9'))
    )
    op.create_index(op.f('ix_BlendComposition_BlendID'), 'BlendComposition', ['BlendID'], unique=False)
    # ### end Alembic commands ###
